global:
  resolve_timeout: 5m
  smtp_smarthost: 'smtp.sina.com:25'
  smtp_from: 'alerta_2019@sina.com'
  smtp_auth_username: 'alerta_2019@sina.com'
  smtp_auth_password: '7d65252a397665cd'

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 4h
  receiver: 'alerta'
  routes:
  - receiver: "alerta"
    group_by: ['alertname','instance','timestamp']
    repeat_interval: 24h
    continue: true
  - receiver: 'email'
    group_by: ['alertname','instance']
    repeat_interval: 24h
    group_interval: 4h
    match:
      alertname: "tomcat error for gj"
receivers:
- name: "alerta"
  webhook_configs:
  - url: 'http://alerta.sit.caijj.net/api/webhooks/prometheus'
    send_resolved: true
    http_config:
      basic_auth:
        username: admin@alerta.io
        password: alerta
- name: 'email'
  email_configs:
  - to: 'xiaojun@lattebank.com,gongjian1746@lattebank.com'
    headers: {Subject: "[ERROR] 日志告警 -for tomcat"}

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']
