version: '2'
services:
  elastalert:
    image: docker.io/bitsensor/elastalert:3.0.0-beta.0
    ports:
      - 3030:3030
      - 3333:3333
    volumes:
      - ./config/elastalert.yaml:/opt/elastalert/config.yaml
      - ./config/elastalert-test.yaml:/opt/elastalert/config-test.yaml
      - ./config/config.json:/opt/elastalert-server/config/config.json
      - ./rules:/opt/elastalert/rules
      - ./rule_templates:/opt/elastalert/rule_templates
      - ./src/alerts.py:/opt/elastalert/elastalert/alerts.py
      - ./src/alerts.py:/usr/lib/python2.7/site-packages/elastalert-0.2.0b2-py2.7.egg/elastalert/alerts.py
    container_name: elastalert
    links:
    - "db:elasticsearch"
    depends_on:
    - db
  
  kibana:
    image: kibana:6.7.0
    volumes:
      - ./config/kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - 5601:5601
    container_name: kibana
    depends_on:
    - db
    links:
    - "db:elasticsearch"

  db:
    image: elasticsearch:6.7.0
    ports:
      - 9200:9200
    environment:
      discovery.type: single-node
    container_name: elasticsearch

